version: '2'
services:
  app1:
    build: ./app1
    volumes:
      - ./app1/:/app
    ports:
      - "8090:8090"
    environment:
      - PORT=8090
  app2:
    build: ./app2
    volumes:
      - ./app2/:/app
    ports:
      - "8091:8091"
    environment:
      - PORT=8091
  app3:
    build: ./app3
    volumes:
      - ./app3:/app
    ports:
      - "8092:8092"
    environment:
      - PORT=8092
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
